server:
  port: 8080

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}

service:
  account:
    url: ${ACCOUNT_SERVICE_URL}
  transaction:
    url: ${TRANSACTION_SERVICE_URL}
  payment:
    url: ${PAYMENT_SERVICE_URL}
  analytics:
    url: ${ANALYTICS_SERVICE_URL}
  report:
    url: ${REPORT_SERVICE_URL}

logging:
  level:
    com.finflow.gateway: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.security: WARN

management:
  tracing:
    sampling:
      probability: 0.1
