apiVersion: v1
kind: ServiceAccount
metadata:
  name: finflow-service-account
  namespace: finflow
  labels:
    app.kubernetes.io/part-of: finflow-platform
  annotations:
    # IRSA — IAM Roles for Service Accounts for AWS EKS
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/finflow-service-role
