apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: finflow
  labels:
    app: fraud-detection-service
spec:
  type: ClusterIP
  selector:
    app: fraud-detection-service
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
    - name: grpc
      port: 9001
      targetPort: 9001
      protocol: TCP
