apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: finflow
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
