apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator-service
  namespace: finflow
  labels:
    app: saga-orchestrator-service
spec:
  type: ClusterIP
  selector:
    app: saga-orchestrator-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
