apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: finflow
  labels:
    app: transaction-service
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
