apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: finflow
  labels:
    app: account-service
    app.kubernetes.io/part-of: finflow-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8082"
  ACCOUNT_DB_URL: "jdbc:postgresql://account-db-service:5432/account_db"
  ACCOUNT_DB_USERNAME: "finflow"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "finflow"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KEYCLOAK_ISSUER_URI: "http://keycloak:9090/realms/finflow"
  KEYCLOAK_JWKS_URI: "http://keycloak:9090/realms/finflow/protocol/openid-connect/certs"
  KEYCLOAK_SERVER_URL: "http://keycloak:9090"
  KEYCLOAK_REALM: "finflow"
  KEYCLOAK_CLIENT_ID: "finflow-internal"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
  OTEL_SERVICE_NAME: "account-service"
