apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: finflow
  labels:
    app: analytics-service
    app.kubernetes.io/part-of: finflow-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8088"
  ANALYTICS_DB_URL: "jdbc:postgresql://analytics-db-service:5432/analytics_db"
  ANALYTICS_DB_USERNAME: "finflow"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KEYCLOAK_ISSUER_URI: "http://keycloak:9090/realms/finflow"
  KEYCLOAK_JWKS_URI: "http://keycloak:9090/realms/finflow/protocol/openid-connect/certs"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
  OTEL_SERVICE_NAME: "analytics-service"
