apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-gateway-config
  namespace: finflow
  labels:
    app: graphql-gateway
    app.kubernetes.io/part-of: finflow-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8081"
  ANALYTICS_SERVICE_URL: "http://analytics-service:8088"
  REPORT_SERVICE_URL: "http://report-service:8089"
  ACCOUNT_SERVICE_URL: "http://account-service:8082"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KEYCLOAK_ISSUER_URI: "http://keycloak:9090/realms/finflow"
  KEYCLOAK_JWKS_URI: "http://keycloak:9090/realms/finflow/protocol/openid-connect/certs"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
  OTEL_SERVICE_NAME: "graphql-gateway"
