apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-config
  namespace: finflow
  labels:
    app: report-service
    app.kubernetes.io/part-of: finflow-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8089"
  REPORT_DB_URL: "jdbc:postgresql://report-db-service:5432/report_db"
  REPORT_DB_USERNAME: "finflow"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET_NAME: "finflow-reports"
  S3_PRESIGNED_URL_EXPIRY_MINUTES: "60"
  KEYCLOAK_ISSUER_URI: "http://keycloak:9090/realms/finflow"
  KEYCLOAK_JWKS_URI: "http://keycloak:9090/realms/finflow/protocol/openid-connect/certs"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:4318/v1/traces"
  OTEL_SERVICE_NAME: "report-service"
